"""Source-backed local magazine pages. Place observations are never synthesized as visits."""
from html import escape as e
from urllib.parse import quote
from pathlib import Path
import json,datetime,email.utils,csv,io
DISTRICTS={'downtown':('Downtown','Start with the thing you came for.','downtown'),'sofa':('SoFA','Art first. The rest can follow.','downtown'),'japantown':('Japantown','Give the afternoon some room.','japantown')}
def link(url,label):return '<a href="'+e(url,quote=True)+'"'+(' target="_blank" rel="noopener noreferrer"' if url.startswith('https://') else '')+'>'+e(label)+'</a>'
def photo(P,key,caption=None):
 p=P[key]
 return '<figure class="local-photo"><img src="assets/'+p['file']+'" alt="'+e(p['alt'])+'" loading="lazy"><figcaption>'+e(caption or p['alt'])+' · '+e(p['author'])+' · '+link('sources.html#local-photography','Photo credits')+'</figcaption></figure>'
def cards(places):
 return '<div class="places-grid">'+''.join('<article class="place-card" data-place data-district="'+p['district']+'" data-kind="'+e(p['category'])+'" data-search="'+e((p['name']+' '+p['address']+' '+p['angle']).lower(),quote=True)+'"><div class="place-top"><span>'+DISTRICTS[p['district']][0]+'</span><span>'+e(p['category'])+'</span></div><h3>'+link('place-'+p['id']+'.html',p['name'])+'</h3><p>'+e(p['angle'])+'</p><div class="place-bottom"><span>'+e(p['window'])+'</span>'+link('place-'+p['id']+'.html','Read the details ↗')+'</div></article>' for p in places)+'</div>'
def district_cards():
 return '<div class="district-grid">'+''.join('<a href="neighborhood-'+id+'.html"><span>0'+str(i+1)+' / NEIGHBORHOOD NOTES</span><h3>'+v[0]+'</h3><p>'+v[1]+'</p><strong>Make a plan ↗</strong></a>' for i,(id,v) in enumerate(DISTRICTS.items()))+'</div>'
def home(places,P,issue):
 return '''<section class="offclock-hero" data-edition-end="'''+e(issue.get('ends',issue['date']))+'''"><div class="wrap offclock-grid"><div><p class="eyebrow">LOUD LOCAL / SAN JOSE OFF THE CLOCK</p><h1>YOUR CITY.<br>YOUR OWN<br><em>GOOD TIME.</em></h1><p>Art after work. A proper afternoon out. A show worth planning around. Start with the details that make a plan work.</p><div class="hero-actions"><a class="btn dark" href="places.html">Find your next stop</a><a class="text-button" href="off-the-clock.html">Read this week’s edition ↗</a></div><div class="cover-count"><b>20</b><span>PLACES<br>THREE NEIGHBORHOODS</span></div></div>'''+photo(P,'downtown','Downtown San Jose, seen from Circle of Palms')+'''</div></section><div class="culture-strip"><span>LOCAL CULTURE</span><b>✳</b><span>GOOD QUESTIONS</span><b>✳</b><span>DETAILS THAT MATTER</span></div><section class="section"><div class="wrap"><div class="section-head"><div><p class="eyebrow">'''+e(issue['range'])+'''</p><h2>OFF THE CLOCK.</h2><p>'''+e(issue['intro'])+'''</p></div><a href="off-the-clock.html">Open the edition ↗</a></div><div class="edition-teasers">'''+''.join('<a href="off-the-clock-'+issue['date']+'.html#'+x['id']+'"><span>'+e(x['label'])+'</span><h3>'+e(x['title'])+'</h3><p>'+e(x['text'])+'</p></a>' for x in issue['items'][:3])+'''</div></div></section><section class="section soft"><div class="wrap"><p class="eyebrow">THREE WAYS INTO THE CITY</p><h2>PICK A NEIGHBORHOOD.</h2>'''+district_cards()+'''</div></section><section class="section"><div class="wrap"><div class="section-head"><div><p class="eyebrow">THE USEFUL DETAIL</p><h2>FIND YOUR KIND OF PLAN.</h2></div><a href="places.html">All 20 places ↗</a></div>'''+cards([places[i] for i in [1,7,14,16]])+'''</div></section><section class="section source-band"><div class="wrap"><div><p class="eyebrow">A PAPER TRAIL FOR YOUR PLANS</p><h2>CHECKED SOURCES.<br>CLEAR LIMITS.</h2><p>Each profile names its source and review date. These are researched planning notes. Hours, event conditions, and source changes stay visible.</p><a href="local-methodology.html">How the local guide works ↗</a></div><div><h3>Still curious about the labels?</h3><p>The original cannabis brand directory and consumer guides remain part of LOUD LOCAL.</p><a href="brands.html">Explore the brand atlas ↗</a><p><a href="off-the-clock.xml">Follow the weekly RSS feed ↗</a></p></div></div></section>'''
def directory(places):
 return '''<section class="section"><div class="wrap"><div class="place-controls"><label>Search places<input type="search" id="place-search" placeholder="A name, street, or idea…"></label><label>Neighborhood<select id="place-district"><option value="all">All three</option>'''+''.join('<option value="'+k+'">'+v[0]+'</option>' for k,v in DISTRICTS.items())+'''</select></label><label>What are you in the mood for?<select id="place-kind"><option value="all">Everything</option>'''+''.join('<option>'+e(k)+'</option>' for k in sorted({p['category'] for p in places}))+'''</select></label></div><p id="place-count" aria-live="polite">20 places</p>'''+cards(places)+'''<p id="place-empty" hidden>No matches. Try another neighborhood or a shorter search.</p><p class="small">Selection: 20 places across Downtown, SoFA, and Japantown, chosen for different kinds of cultural outings. This is a starting collection, not a ranking. “Check hours” means a dependable opening window has not been established here.</p><p><a href="local-places.csv" download>Download the place index (CSV)</a> · <a href="local-methodology.html">Sources and method</a></p></div></section>'''
def profile(p,places,status):
 check=status.get('sources',{}).get(p['source'],{})
 note=''
 if check.get('status')=='error':note='<p class="notice">The latest automated source check failed. The notes below retain their original review date.</p>'
 elif check.get('status')=='changed':note='<p class="notice">The source page has changed since its earlier snapshot. The notes below keep their review date until the details are reviewed.</p>'
 nearby=[x for x in places if x['district']==p['district'] and x['id']!=p['id']][:3]
 return '<section class="section"><div class="wrap article-layout"><article class="article">'+note+'<p class="eyebrow">THE REASON TO LOOK CLOSER</p><h2>'+e(p['angle'])+'</h2><p>'+e(p['description'])+'</p><h2>The detail that changes the plan</h2><p>'+e(p['planning'])+'</p><h2>Timing matters</h2><p>'+e(p['timing'])+'</p><h2>Where this information comes from</h2><p>'+link(p['source'],'Open the source reference ↗')+'. Source review: '+p['reviewed']+'. '+('Additional address reference: '+link(p['sources_extra'][0],'Japantown Business Association')+'.' if p.get('sources_extra') else '')+'</p><p>These are source-based planning notes. We have not assigned firsthand ratings for sound, service, crowds, or accessibility. Confirm time-sensitive details with the venue.</p><p>'+link('neighborhood-'+p['district']+'.html','Read the '+DISTRICTS[p['district']][0]+' guide ↗')+'</p></article><aside class="sidebox"><p class="eyebrow">AT A GLANCE</p><h3>'+e(p['name'])+'</h3><dl>'+''.join('<dt>'+a+'</dt><dd>'+e(b)+'</dd>' for a,b in [('Address',p['address']+', San Jose'),('Category',p['category']),('Time window',p['window']),('Cost context',p['cost']),('Planning',p['booking']),('Reviewed',p['reviewed'])])+'</dl>'+link('https://www.google.com/maps/search/?api=1&query='+quote(p['name']+' '+p['address']+' San Jose'),'Locate the address ↗')+'</aside></div></section><section class="section soft"><div class="wrap"><h2>Keep exploring '+DISTRICTS[p['district']][0]+'.</h2>'+cards(nearby)+'</div></section>'
GUIDES={
'downtown':('Downtown, with one good anchor.','A gallery, a show, or a film. Choose the fixed part first.',[
('Start with the appointment','Downtown offers different kinds of cultural stops, but they do not share one schedule. A ticketed show at the Hammer, Civic, or Improv should set the rest of the plan. Read door time, start time, and any visit requirements on the specific event page.'),
('A Friday art option','The Museum of Art’s source page lists a later Friday closing than its other regular opening days. If you want an art-centered after-work visit, check that schedule and the current exhibition before choosing your arrival time.'),
('A flexible food meeting point','San Pedro Square Market can provide a meeting point for people with different food preferences. Its building hours are not proof that every vendor serves throughout that window. Confirm the counter you want and give your group a precise meeting point.'),
('If you have two hours','As an editorial planning framework, reserve most of the time for one main activity and leave a buffer for arrival and moving between stops. Two hours is not a promise that a full performance and dinner will fit. For the Tech, distinguish a gallery visit from a complete IMAX screening.'),
('The practical check','Use the exact addresses in the profiles to assess the route for your group. Walking distances, street conditions, and access requirements are not field-tested here. A compact district still needs a realistic travel buffer.')]),
'sofa':('SoFA, before and after the curtain.','One neighborhood. Several different clocks.',[
('Choose the kind of art time you want','MACLA and Anno Domini both provide gallery opportunities, but their ordinary schedules differ. MACLA’s published regular hours end at 5pm; Anno Domini lists later Thursday and Friday hours. An event night is a separate calendar entry, not a promise that every gallery stays open.'),
('Put the show in the middle of the plan','California Theatre, San Jose Stage, and City Lights have different programmes. Pick a production and date, then work backward from the start time. Read any runtime and intermission information before making a later commitment.'),
('Leave a flexible space for food','SoFA Market provides several vendor options on South First Street. Nirvana Soul’s Downtown location is also on South First, while Haberdasher is on West San Salvador and publishes evening hours. Treat each business’s schedule independently.'),
('A two-hour gallery plan','For a short outing, choose one gallery as the purpose of the visit and one nearby stop as optional. The sequence is a planning suggestion rather than a timed walking tour. If the gallery closes before your start time, choose a confirmed event instead.'),
('Know which street','City Lights is on South Second Street. The California Theatre, Stage, and the profiled galleries are on South First. Use venue names and exact addresses when meeting someone; “in SoFA” is not a complete meeting instruction.')]),
'japantown':('Japantown deserves an afternoon.','The early closing times are part of the story.',[
('Coffee first, if coffee matters','Roy’s official schedule ends at 2pm on weekdays and 3pm on weekends. That makes it an early part of an outing. A generic “coffee after the museum” plan can miss the café’s published window.'),
('Make room for history','JAMsj lists Thursday–Sunday afternoons, noon–4pm. Set aside time for its exhibits rather than treating the museum as a quick photo stop. Its own visit page provides admission information and holiday exceptions.'),
('Look at what the shops actually make and carry','Shuei-Do is associated with manju; Nichi Bei Bussan’s site presents fabrics, clothing, gifts, and home goods. Kogura is listed among the neighborhood’s specialty shops. They are distinct stops with their own visiting details, not interchangeable entries in a shopping list.'),
('A two-hour framework','Choose the museum as the main stop, with a café or shop before it if the timing works. Roy’s, Shuei-Do, Nichi Bei Bussan, and Kogura are on Jackson Street; JAMsj is on North Fifth. Check the addresses and your own travel needs rather than assuming every stop will fit.'),
('If your free time starts later','Jtown Pizza’s location page is one place to check for a food plan, but its current hours still need confirmation. Do not turn an afternoon museum and shop route into an evening itinerary without checking each business.')])}
def neighborhood(id,places,P):
 title,dek,sections=GUIDES[id]
 return photo(P,DISTRICTS[id][2],DISTRICTS[id][0]+' context; photograph is not a current venue inspection')+'<section class="section"><div class="wrap article"><p class="eyebrow">A PRACTICAL READING OF THE NEIGHBORHOOD</p>'+''.join('<h2>'+e(h)+'</h2><p>'+e(p)+'</p>' for h,p in sections)+'<p class="small">Sources reviewed September 23, 2026. Timing suggestions are editorial planning guidance. Each linked profile provides its original sources and review date.</p></div></section><section class="section soft"><div class="wrap"><h2>The places behind the plan.</h2>'+cards([p for p in places if p['district']==id])+'</div></section>'
def edition(issue,places,P):
 return '<section class="section"><div class="wrap article"><p class="edition-date">'+e(issue['range'])+' · Source review '+issue['reviewed']+'</p><p>'+e(issue['intro'])+'</p>'+''.join('<section id="'+x['id']+'"><p class="eyebrow">'+e(x['label'])+'</p><h2>'+e(x['title'])+'</h2><p>'+e(x['text'])+'</p><p>'+link(x['source'],'Read the original reference ↗')+'</p></section>' for x in issue['items'])+'<h2>Keep a copy of the plan.</h2><p>'+link('places.html','Browse all 20 places')+' · '+link('off-the-clock.xml','Follow new editions with RSS')+'</p><p class="small">This dated edition is an archive, not a live availability check. Events and exhibitions may change. The venue’s current notice takes precedence.</p></div></section>'
def publish(page,sub,root,out,url,P):
 places=json.loads((root/'data/local-places.json').read_text());status=json.loads((root/'data/local-source-status.json').read_text()) if (root/'data/local-source-status.json').exists() else {}
 issues=json.loads((root/'data/local-editions.json').read_text())
 page('index.html','San Jose off the clock','20 sourced places, three neighborhood guides, and a weekly local culture edition.',home(places,P,issues[-1]),'index.html',{'about':{'@type':'Place','name':'San Jose, California'}})
 page('places.html','20 places for your San Jose downtime','Explore source-backed places in Downtown, SoFA, and Japantown.',sub('FIND YOUR NEXT STOP.','Search the name. Check the timing. Make it your own.','THE LOCAL INDEX')+directory(places),'places.html')
 for p in places:page('place-'+p['id']+'.html',p['name']+' | local planning notes',p['angle'],sub(p['name'],p['angle'],DISTRICTS[p['district']][0])+profile(p,places,status),schema={'@type':'Article','headline':p['name']+' | local planning notes','citation':[p['source']],'dateModified':p['reviewed'],'about':{'@type':'Place','name':p['name'],'address':p['address']+', San Jose, CA'}})
 for id,(title,dek,_) in GUIDES.items():page('neighborhood-'+id+'.html',title,dek,sub(title,dek,'NEIGHBORHOOD NOTES')+neighborhood(id,places,P),schema={'@type':'Article','headline':title,'dateModified':'2026-09-23','citation':[p['source'] for p in places if p['district']==id]})
 for issue in issues:page('off-the-clock-'+issue['date']+'.html',issue['title'],issue['intro'],sub('OFF THE CLOCK.',issue['title'],'THE WEEKLY EDITION')+edition(issue,places,P),schema={'@type':'Article','headline':issue['title'],'datePublished':issue['date'],'dateModified':issue['reviewed'],'citation':[i['source'] for i in issue['items']]})
 archive='<section class="section"><div class="wrap"><p>One compact edition of useful local findings. Read the issue date before relying on an event or opening time.</p><div class="guide-grid">'+''.join('<a class="guide-card" href="off-the-clock-'+x['date']+'.html"><p class="eyebrow">'+e(x['range'])+'</p><h2>'+e(x['title'])+'</h2><p>'+e(x['intro'])+'</p><span>Read the edition ↗</span></a>' for x in reversed(issues))+'</div><p>'+link('off-the-clock.xml','Follow the RSS feed ↗')+'</p><p class="small">New editions are scheduled weekly. Email subscription is not enabled; RSS delivers the published editions without collecting your email address.</p></div></section>'
 page('off-the-clock.html','Off the Clock | weekly San Jose culture notes','Dated local culture editions and a subscription-ready RSS feed.',sub('GOOD PLANS START HERE.','A small edition. Useful details. Sources you can check.','OFF THE CLOCK')+archive,'off-the-clock.html')
 method='<section class="section"><div class="wrap article"><h2>What makes this collection useful</h2><p>The pilot compares 20 places across three neighborhoods through practical constraints: timing, booking, address, and cost context. The selection is editorial and is not a ranking or a complete business directory.</p><h2>Evidence, not assumptions</h2><p>Venue sites, public records, business associations, and official tourism references support the profiles. Each has a review date. These are researched guides; no visit, interview, noise measurement, or service test is claimed. Local news may help discover a lead; facts are checked at the original source. Material taken from another publication is attributed when used.</p><h2>What updates automatically</h2><p>Source monitoring records fetch failures and changes to page text. A changed page enters review; it does not silently rewrite hours or prices. The weekly editorial job reviews sources before publishing a dated edition. Monthly checks of the original brand references continue separately.</p><h2>Dates mean different things</h2><p>A source-check timestamp means a page was fetched. A profile review date means its written details were checked. Event dates belong to the event. Old editions remain in the archive with their original dates.</p><h2>Help the information travel</h2><p>'+link('local-places.csv','Download the place index (CSV)')+' · '+link('local-places.json','Read the structured place records (JSON)')+' · '+link('off-the-clock.xml','Follow the RSS feed')+'</p><h2>Source monitor</h2>'
 rows=''.join('<tr><td>'+link(p['source'],p['name'])+'</td><td>'+e(status.get('sources',{}).get(p['source'],{}).get('status','Not yet monitored'))+'</td><td>'+e(status.get('sources',{}).get(p['source'],{}).get('checked_at','')[:10])+'</td></tr>' for p in places)
 method+='<div class="table-scroll"><table><thead><tr><th>Place reference</th><th>Monitor status</th><th>Attempt date</th></tr></thead><tbody>'+rows+'</tbody></table></div></div></section>'
 page('local-methodology.html','Local guide sources and method','Selection, source checks, review dates and downloadable place data.',sub('DETAILS YOU CAN TRACE.','Useful research starts with a clear method.','LOCAL GUIDE METHOD')+method)
 (out/'local-places.json').write_text(json.dumps(places,ensure_ascii=False,indent=2));f=io.StringIO();w=csv.DictWriter(f,fieldnames=['id','name','district','category','address','source','timing','cost','booking','reviewed']);w.writeheader();w.writerows({k:p[k] for k in w.fieldnames} for p in places);(out/'local-places.csv').write_text(f.getvalue())
 items=''.join('<item><title>'+e(x['title'])+'</title><link>'+url+'/off-the-clock-'+x['date']+'.html</link><guid isPermaLink="true">'+url+'/off-the-clock-'+x['date']+'.html</guid><pubDate>'+email.utils.format_datetime(datetime.datetime.fromisoformat(x['date']).replace(tzinfo=datetime.timezone.utc))+'</pubDate><description>'+e(x['intro'])+'</description></item>' for x in reversed(issues))
 (out/'off-the-clock.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>LOUD LOCAL: Off the Clock</title><link>'+url+'/off-the-clock.html</link><description>Useful San Jose culture notes.</description><language>en-us</language>'+items+'</channel></rss>')
